### ISSUE TITLE
Decouple META from the system, leverage token details to adjust for markets and other UI components

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-frontend#59]
This is going to matter shortly, so I'm going to list the required changes there is a primary issue with support older versions of the IDLs and program structure FACK! this will be a bit more tricky, given metaMint and structure was included previously.

- [ ] Update the Autocrat IDL

META References (please note this isn't comprehensive but indicative of where):
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/hooks/useTokens.ts#L30
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/components/Orders/ProposalUnsettledOrderRow.tsx#L133
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/hooks/useInitializeProposal.ts#L102
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/components/ManageDao/TransferTokensButton.tsx#L31
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/components/Proposals/ProposalDetailCard.tsx#L137
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/hooks/useAutocratDebug.ts#L15
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/components/ManageDao/CreateTestTokensCard.tsx#L36
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/components/Markets/ConditionalMarketCard.tsx#L380
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/components/Proposals/JupSwapCard.tsx#L12
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/components/Proposals/MintConditionalTokenCard.tsx#L95
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/components/Proposals/ProposalOrdersCard.tsx#L71
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/contexts/ProposalContext.tsx#L22
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/hooks/useConditionalTokens.ts#L62
- [ ] https://github.com/metaDAOproject/meta-dao-frontend/blob/2e5296ea617fc463a8db2697b30106ae2e7f7f30/lib/openbook.ts#L374
